//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingclinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentSelection
    {
        public int ID { get; set; }
        public string SEX { get; set; }
        public string AGE { get; set; }
        public string WEIGHT { get; set; }
        public string HEIGHT { get; set; }
        public string KLSCALE { get; set; }
        public string GOAL1 { get; set; }
        public string GOAL2 { get; set; }
        public string GOAL3 { get; set; }
        public string GOAL4 { get; set; }
        public string GOAL5 { get; set; }
        public string GOAL6 { get; set; }
    }
}
